#!/usr/bin/env node

/*jslint node: true */
'use strict';

var path = require('path'),
    exec = require('./lib/exec');

console.log('Installing titanium stuff...');

console.log('--- Installing Build Command(s) ---');
exec('ti', ['config', '-a', 'paths.commands', path.join( __dirname , 'plugin')], null, function() {
    console.info('Titanium CLI command installed.');
});


